<?php

namespace MyCompany\ArticleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IdejaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdejaRepository extends EntityRepository
{
}
