security:
    encoders:
        MyCompany\UserBundle\Entity\User: bcrypt
    role_hierarchy:
        ROLE_ADMIN: ROLE_NOVINAR
    providers:
        our_database_users:
            entity:
                class: 'UserBundle:User'
    firewalls:
        secured_area:
            pattern: ^/
            form_login:
                check_path: login_check
                login_path: login_form
            logout:
                path: logout
                target: news_index
            anonymous: null
            remember_me:
                secret: '%secret%'
    access_control:
        -
            path: ^/roles
            roles: ROLE_ADMIN
        -
            path: ^/login
            roles: IS_AUTHENTICATED_ANONYMOUSLY
        -
            path: ^/new$
            roles:
                - ROLE_NOVINAR
        -
            path: ^/\d+/edit$
            roles:
                - ROLE_NOVINAR
        -
            path: ^/\d+/delete$
            roles:
                - ROLE_NOVINAR
        -
            path: ^/ideja$
            roles:
                - ROLE_PLACEHOLDER
                - ROLE_ADMIN
        -
            path: ^/ideja/\d+/edit$
            roles:
                - ROLE_PLACEHOLDER
                - ROLE_ADMIN
